### PR TITLE
Some changes to color theming

### PR DESCRIPTION
**Pull request by ThatGravyBoat**
### What does this PR do?

This PR does several things:
- It changes the theme colors to be records to be immutable.
- It uses codecs instead of json parsing to do reflection.
- It switches to using the `Color` class from resourceful lib to allow for more customizable colors system which includes named colors from css, dynamic colors like rainbow that change over time, additional formats for writing a number like hex string both 0x and # format, int format, and rgb object.
- Remove mixin for color handler and switch it to wrapping on fabric instead to allow for easier extensibility in the future.
- Change color handler to theme handler and make it so that it loads a single file instead of all files in the "colors" folder.

### Why does it need to do this?

- For the immutable we do not want state to be left over from another session as such currently with the reflection and mutable fields what can happen is you use 1 texture pack it changes the color state and then remove it and the state still exists, and while reflection can be fine I generally want to stay away from using reflection for things that can come from external services like a server using a server resource pack.
- The switching to the `Color` class like I said allows for more customization.
- Mixin removal we can use it in the future for other reload listeners.
- Change color handler to use a `SimplePreparableReloadListener` instead is to only load the file we need.

### CODE REVIEW

**Comment by sisby-folk** [comment]
Here's my notes -

- Generifying the fabric listener problem into a class makes sense, looks good.
- Change to the color class looks good, very happy to see many ways to define colors in the json
- Change to SinglePreparableReloadListener is great, again, haven't used that one before.

The only thing I'm not fully convinced about is the change from a reflected static class to many records with static getters and codecs. It looks like it works perfectly well, but I'm concerned that it might be overengineered to the point where it's not accessible and people are going to forget to use it. 

The process to add new color string was adding one field and one line to a json file, but now it's a record parameter, a default parameter, a codec line, a static getter, and a static method call to one of 6 classes.

The inclusion of a built-in `heracles.json` resolves most concerns with partial state - when a resource pack is removed, the built-in theme is loaded from json instead. I'm unsure if you knew about this file, because it's not changed here. There's a minor flaw in this system where if you immediately swap from one incomplete respack theme to another incomplete respack theme, there might be some leftover state, but i'm pretty sure this can be fixed by allowing the reloader to individually process files with the same ID, similar to how tags do so - if that's not possible, more reflection could be used to resolve the problem instead.

Open to hearing your thoughts about this one - I don't think that reflection, in the way that it's used here (setting declared fields to primitives - no object serialization, etc), is any sort of security concern, but I understand wanting to have a system that's similarly codec-based to other parts of the mod.

**Comment by ThatGravyBoat** [comment]
Yeah the reason you provided for a flaw in the state is what I meant sorry if I didnt make that clear what I meant was if you had 2 resource packs that modified state and then remove 1 you will get the combined output of both with only 1 used.

I do understand its over engineered in some ways but in my opinion keeping to the codec nature of the rest of the mod is best, reflection can be bad here for the reason that if someone comes along and adds a field in there without knowing that the whole class can be reflectively changed via a config file it can lead to some bad or unintended things happening, I want it to be explicit that its being added to checking rather than always on.

As for "people are going to forget to use it" that should be caught when PR reviews happen as everyone would be submitting by PRs and when I add features to the mod I also do PRs and rereview them myself and wait a few days for others to also take a look.

**Comment by sisby-folk** [comment]
Yep no all good - I don't see myself adding a bunch more colours to the mod any time soon so it doesn't bother me too much. Feel free to update to add the new colours for buttons and I'll merge in so we can get the other PR rolling.

**Comment by ThatGravyBoat** [comment]
They have been fixed, you can ignore the first commit as that was just me pulling it in with just the color fields as to make it easier to actually fix the conflicts in the second commit.

**Comment by ThatGravyBoat** [comment]
I would suggest doing a squash merge

**Pull request merged**
